### ISSUE TITLE
Invalid Version "0.1"

### ISSUE THREAD

**Issue by EliteJaguar** [craigster1991/arctis-battery-win-app#3]
Hello, when trying to run the `npm run build` command, an error appears in the command prompt. 

![image](https://user-images.githubusercontent.com/64319717/126523589-84f75f57-c792-47f3-a10c-0340dd03d4c4.png)

The full log is below:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.16.0
4 verbose stack Error: Invalid version: "0.1"
4 verbose stack     at Object.fixVersionField (C:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\fixer.js:191:13)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:32:38
4 verbose stack     at Array.forEach (<anonymous>)
4 verbose stack     at normalize (C:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:31:15)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:429:5)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:161:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:382:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:123:16
4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
5 verbose cwd E:\Documents\arctis-battery-win-app
6 verbose Windows_NT 10.0.19042
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
8 verbose node v14.16.0
9 verbose npm  v6.14.11
10 error Invalid version: "0.1"
11 verbose exit [ 1, true ]
```

Wondering if you know what the issue is?

TIA

**Comment by EliteJaguar** [comment]
Turns out I was being an idiot. Great work with this, really useful!

**Comment by Denny966** [comment]
What was the fix? I'm having the same issue

**Comment by craigster1991** [comment]
@Denny966 I've just pushed a fix for this, it was a node semantic versioning issue
